"""Initial Migration

Revision ID: 4902c8f28255
Revises: b181afa95e5c
Create Date: 2021-09-25 09:57:52.156224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4902c8f28255'
down_revision = 'b181afa95e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('user', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'user')
    op.drop_column('pitch', 'category')
    op.drop_column('comment', 'user')
    # ### end Alembic commands ###
